### ISSUE TITLE
`expectBody()` doesn't handle a `RegExp` properly

### ISSUE THREAD

**Issue by avoidwork** [avoidwork/tiny-httptest#2]
woodland tests:

```console
Running "mochaTest:test" (mochaTest) task


  Valid Requests
    1) GET / (200 / 'Success')


  0 passing (15ms)
  1 failing

  1) Valid Requests GET / (200 / 'Success'):
     Error: Unexpected body value: Hello World! !== /^Hello World!$/
    at TinyHTTPTest.test (D:\Projects\woodland\node_modules\tiny-httptest\lib\tinyhttptest.js:266:10)
    at TinyHTTPTest.process (D:\Projects\woodland\node_modules\tiny-httptest\lib\tinyhttptest.js:200:9)
    at IncomingMessage.done (D:\Projects\woodland\node_modules\tiny-httptest\lib\tinyhttptest.js:86:12)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by avoidwork** [comment]
The arguments are reversed in `test()`:

```
else if (arg instanceof RegExp) {
	valid = arg.test(value);
}
```

`arg` is the response body, `value` is the expectation.
